### ISSUE TITLE
Simplify date/time handling

### ISSUE THREAD

**Issue by ghost** [370-Alexa-Project/CS370_Echo_Demo#13]
The Alexa skill currently handles date/time formatting in a cumbersome way. The code can be simplified by removing calls to .toLocal{Date,Time}() on the localDateTime object.

Also, localDateTime should be named zonedDateTime, and the imports of LocalDate and LocalDateTime are extraneous.

**Comment by ghost** [comment]
To further optimize, the use of TimeZone could be changed to ZoneId directly, so that a conversion is not required. `ZoneId.of("America/Los_Angeles")` produces the ZoneId required for the .atZone() method of LocalDateTime.

**Comment by jorgecanchola** [comment]
Simplify date/time handling
