### ISSUE TITLE
Update 'connected' variable in DbConnection Class

### ISSUE THREAD

**Issue by eBucher** [370-Alexa-Project/CS370_Echo_Demo#14]
In the DbConnection class, there is a private variable named 'connected' which should be true if the user is connected to the database (after getRemoteConnection() is called) or false if they are not connected. Currently, it is not being updated to true when getRemoteConnection() is called. The code should be fixed so that the variable is up to date at all times.

**Comment by ghost** [comment]
There might be a method on the Connection object that we can provide a wrapper for, in lieu of duplicating that state.

**Comment by eBucher** [comment]
The connection class that DbConnection is built off of has an isValid( ) method that checks whether there is a connection to the database. It works by sending a simple query, which seems more reliable than tracking it ourselves (especially since it is possible that you could lose connection, but the variable would not be updated). 

You could call this at the beginning of each intent handler method, but then you would be querying the database twice - once to test for connection and then once with your actual query for information. I'm thinking about adding key/value to the map returned by the runQuery( ) method that would reflect whether the app was able to connect, so that we don't crash if there is no connection. Then, the handler methods would look like this:

```
if(!results.get("WasAbleToConnect").get(0))
    return newTellResponse("Sorry, I could not access my source of information at the moment", false);
else
    // Do normal response stuff
```

**Comment by ghost** [comment]
If the test is simply doing a query, then I guess we can just do whatever query we wanted to do in the first place and check if the result is null to find out if we were connected or not.
