### ISSUE TITLE
Specify schema in DbConnection

### ISSUE THREAD

**Issue by ghost** [370-Alexa-Project/CS370_Echo_Demo#15]
We should add a property to the DbConnection.xml file for `schemaName` and set the schema on the connection with it, so that we don't have to specify the schema in our query strings.

**Comment by eBucher** [comment]
Working on this.

**Comment by eBucher** [comment]
The schema can now be specified in the DbCredentials.xml file. If the tag is left empty, you have to say the name of the schema in your query. Otherwise, it is now implied if the tag is filled in.
