### ISSUE TITLE
Strip HTML tags from calendar fields

### ISSUE THREAD

**Issue by ghost** [370-Alexa-Project/CS370_Echo_Demo#16]
Certainly this is already a solved problem, we must simply find the code that already exists to do this. A robust solution would be non-trivial to implement from scratch.

This could be a stored procedure that runs on the database:
- latency is minimized by reducing the amount of data that needs to be transferred
- SSML transformations can be stored in the database and run after HTML is stripped but before sending the data to the Alexa skill, thus avoiding the latency of an additional round trip

I will look into what language extensions can be added on RDS for making this task more approachable, but there are probably existing solutions in PL/pgSQL.

**Comment by ghost** [comment]
Amazon RDS supports four language extensions: Perl, pgSQL, Tcl, and JavaScript (via the V8 JavaScript engine).

https://aws.amazon.com/rds/postgresql/

**Comment by eBucher** [comment]
In addition to this, it looks like we may need need to replace &s with the word "and". Currently, any names with ampersands in them cause Alexa's response to not work.

**Comment by ghost** [comment]
Thanks to input from Jessica and Aaron, the new, cleaner strategy is to perform this transformation in the scraper and discard the original descriptions from the calendars, storing only the stripped versions instead. This reduces latency to a minimum in the Alexa skill, is optimally space efficient in the database, and scales cleanly in the scraper.

Here's a checklist to help track the progress of this issue:
- [ ] Find a Python library to strip HTML tags
- [ ] Implement a Python function to strip HTML tags from a string
- [ ] Integrate strip function in the scraper
- [ ] Redeploy updated scraper on Lambda
- [ ] Rebuild the database

**Comment by ghost** [comment]
We currently have no plans to use the fields that contain HTML, so I'm benching this issue.
