### ISSUE TITLE
Find commonly mispronounced words

### ISSUE THREAD

**Issue by ghost** [370-Alexa-Project/CS370_Echo_Demo#21]
Alexa isn't perfect. Sometimes she might mispronounce a word, or say a name with awkward inflection. But we can help.

One idea is to find all the unique words from the calendar, manually select from that list all the words that Alexa might have trouble with, try those words on the test page or with a test skill, and create SSML markup for the words that were mispronounced.

The result should be a list of words and the corresponding SSML versions that can be parsed into a database table or used to generate code.

**Comment by ghost** [comment]
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference

**Comment by ezquire** [comment]
been reading up on SSML and i think i can tackle this
