### ISSUE TITLE
A user should be able to traverse the list of events

### ISSUE THREAD

**Issue by ghost** [370-Alexa-Project/CS370_Echo_Demo#23]
Amazon provides common intents for cursor control functions, such as AMAZON.NextIntent and AMAZON.PreviousIntent.  We want to take advantage of these to allow a user to browse through the calendar events once they find a starting position.  For example, there are often multiple events starting at the same time, so a user might want to go through the events one at a time to find the one they are looking for.

_Consider how we should instruct the user how to navigate through the list of events._

**Comment by ghost** [comment]
Removing this from the milestone for lack of time.

**Comment by ezquire** [comment]
Ok so I think I can get this to work, let me add some functionality to the switch for builtin intents that can handle those two built ins and I think all we need to do (which may be incredibly hard) is figure out where in the list the user happens to be
