### ISSUE TITLE
A user should be able to get a list of events for a given date and/or time

### ISSUE THREAD

**Issue by ghost** [370-Alexa-Project/CS370_Echo_Demo#24]
Instead of just reading off whichever event is next, allow a user to specify some date or time for which to get a list of events. The fallback behavior when no date or time is specified might be to get the next event. Amazon has built-in slot types for date and time that can be used.

**Comment by ghost** [comment]
Built-in slot types are documented here: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interaction-model-reference#slot-types

**Comment by eBucher** [comment]
This was all I worked on yesterday, It seems like it needs to be broken up into a couple of different steps to be able to come up with the right queries.
1. Change the date that Alexa gives you, which comes in yyyy-MM-dd to a timestamp in the GMT timezone that atleast has yyyy-MM-dd hh.
2. Create another time stamp string that is 24 hours later.
3. Run a query that says something like, "SELECT \* FROM events WHERE start > beginningTime AND start < endTime."
4. Go through each of the event start times returned from the query, and change them to "hh:mm a" format to be read by Alexa.

**Comment by eBucher** [comment]
Also, it would probably be best to make some of these steps into separate methods so we can keep the intent handler methods less cluttered with code for manipulating dates.

**Comment by ghost** [comment]
https://www.postgresql.org/docs/9.5/static/datatype-datetime.html
https://www.postgresql.org/docs/9.5/static/functions-datetime.html

**Comment by ghost** [comment]
We could do something like `SELECT * FROM event_info WHERE date_trunc('day', start) = date_trunc('day', requestedDate)` to get a list of events on the requested date.

**Comment by ghost** [comment]
Additional details in #33
