### ISSUE TITLE
Change summary variable to name variable

### ISSUE THREAD

**Issue by jorgecanchola** [370-Alexa-Project/CS370_Echo_Demo#25]
Summary variable needs to be changed to the name variable in the database.

**Comment by cyberwolf30** [comment]
Summary variable needs to be changed to the name variable in the database.

**Comment by ghost** [comment]
The columns in the events table are based on the names of the fields in the calendars. A view could rename the columns to present them as expected by the Alexa skill, or we could rename all the columns in the schema itself, recreate the database from scratch, and update everywhere they are used across the whole project.

**Comment by ghost** [comment]
To avoid confusion, the name "title" was chosen instead of "name".

To-Do:
- [x] ~~Rename column in Database/schema.sql~~
- [x] ~~Rename where used in Scraper/scraper.py~~
- [ ] Rename where used in the Alexa skill

**Comment by ghost** [comment]
This still needs to be renamed in the Alexa skill (in both CalendarHelper and CalendarConversation).
It should be a simple search and replace, but review the changes before you commit just to be sure.
