### ISSUE TITLE
Make re-prompt longer when asking for response / Change wording of responses

### ISSUE THREAD

**Issue by jessdevincenzi** [370-Alexa-Project/CS370_Echo_Demo#40]
Currently Alexa gives a very short re-prompt time and makes it hard for the user to come up with something to respond with. Possibly increase response time to 15 seconds.

**Comment by ghost** [comment]
There doesn't appear to be a baked-in way to adjust the pause.

As a workaround, we could try manually inserting breaks in the response SSML or the reprompt SSML.

Javadoc References:
[Reprompt](https://developer.amazon.com/public/binaries/content/assets/javadoc/ask-java-library-3/com/amazon/speech/ui/reprompt.html)
[SpeechletResponse](https://developer.amazon.com/public/binaries/content/assets/javadoc/ask-java-library-3/com/amazon/speech/speechlet/speechletresponse.html)

**Comment by ghost** [comment]
Even if we add a pause to the beginning of a reprompt, Alexa won't be listening during the break. The only way to interrupt her seems to entail losing the current session, so dealing with this will require more work around maintaining state across multiple sessions, which is outside the scope of this sprint, so I'm benching this issue for now.

**Comment by ghost** [comment]
Ultimately it does not make sense to artificially pad the reprompt message, however we have updated the responses to be more contextually appropriate.
