### ISSUE TITLE
Deal with relative dates such as this weekend or tomorrow

### ISSUE THREAD

**Issue by jessdevincenzi** [370-Alexa-Project/CS370_Echo_Demo#42]
Right now the user can only ask about what's happening next or what's happening on a specific day. We want to be able to ask what's happening tomorrow and what is happening this upcoming weekend.

When dealing with this we want to consider what information the user wants to hear. Get them to narrow it down with re-prompts. Don't blurb out unnecessary shit. YO.

**Comment by ghost** [comment]
We already handle things like "tomorrow" and "next Tuesday" and even stuff like "on Halloween".

What we don't handle yet (Jeff specifically asked us to not worry about it yet last time) is ranges broader than a day. For example, "this weekend" or "next week" represent more than one day.

The [AMAZON.DATE](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interaction-model-reference#slot-types) slot type supports these expressions and represent them to us in a standard, easy format.  We need to add the parsing of the date string passed in the slot and adapt our handler to support ranges of dates.
