### ISSUE TITLE
Clean Up intents in the Amazon Developer Portal

### ISSUE THREAD

**Issue by ezquire** [370-Alexa-Project/CS370_Echo_Demo#44]
We have a bunch of random intents in our skill that pertain to the knock knock joke, do we still need these? or can we clean up the portal side a bit? Thoughts?

**Comment by ezquire** [comment]
![capture](https://cloud.githubusercontent.com/assets/20214762/19750778/082f3462-9ba9-11e6-92a3-7d54161f2531.PNG)
this is what i mean

**Comment by ghost** [comment]
I'm on board with getting rid of these and cleaning up the utterances as mentioned in #45 as well.

We could also get rid of the `com.neong.voice.example` package entirely.
