### ISSUE TITLE
Update words Alexa uses to acknowledge the User's request

### ISSUE THREAD

**Issue by jessdevincenzi** [370-Alexa-Project/CS370_Echo_Demo#55]
Currently, for every request the User asks Alexa, she responds with "Okay" then lists the events or information that was asked for. We want to update her response so that she uses different words to acknowledge what the user said.

Ex:
U - Alexa, what's happening on [date]
A - Okay, there are [events on this day]
U - Tell me about sports
A - **Sure,** there are # [category name] events that day
U - What is the price of [event name]
A - **The price of** [event name] is ...

Whether to hardcode these responses or create a list of response words that we could iterate through is still up in the air.

**Comment by pineda756** [comment]
Fixed by #56
