### ISSUE TITLE
Update default response message

### ISSUE THREAD

**Issue by ghost** [370-Alexa-Project/CS370_Echo_Demo#6]
The default response when we get a request that does not match an intent we understand should be updated to be more helpful to the user.

**Comment by ghost** [comment]
In terms of the Product Overview document where we are in theory supposed to combine the projects from all the classes at the end, this doesn't work out that easily because it would modify code that all the projects share, in the Speechlet. We could implement a generic mechanism for any Conversation to register their own help messages and have the Speechlet list all the help messages, but that's probably stepping a bit out of bounds.

On the other hand, it would lead to a better user experience for demos, and we can always revert it later.

**Comment by jessdevincenzi** [comment]
- you can ask me about events in the calendar
- can ask about events on a specific day
- can ask about upcoming events tomorrow, this weekend, or next week

**Comment by ghost** [comment]
Updated in #51
