### ISSUE TITLE
Utterance Issues

### ISSUE THREAD

**Issue by eBucher** [370-Alexa-Project/CS370_Echo_Demo#65]
Here are a list of known utterance issues that seem reasonable for a user to say, but Alexa is thinking that the user is trying to invoke a different intent. More will be added as they are found.

> 1. Utterance: Clubs
> Expected Intent: ClubsCategoryIntent
> Actual Intent: AllCategoryIntent

Update: fixed by 50d39e48a3edb3ac5b8145e80ad0fa1d2bd30b17

**Comment by ghost** [comment]
> 2
>     Utterance: how much is it
>     Expected Intent: GetFeeDetailsIntent
>     Actual Intent: AllCategoryIntent

Update: fixed by 50d39e4

**Comment by eBucher** [comment]
> 3
> Utterance: Tell me the sports events
> Expected Intent: SportsCategoryIntent 
> Actual Intent: NextEventIntent

Update: fixed by 50d39e48a3edb3ac5b8145e80ad0fa1d2bd30b17

**Comment by ezquire** [comment]
Ok so i think this issue can be rolled into the other one any objections?

**Comment by ghost** [comment]
> 4
> Utterance: Where is it
> Expected Intent: LocationDetailIntent
> Actual Intent: AllCategoryIntent

Update: fixed by 50d39e4

**Comment by ghost** [comment]
> I think we need versions of the detail intent utterances that don't have slots.

Update: fixed by 50d39e4

**Comment by ghost** [comment]
> 5
> Utterance: What's happening Monday
> Expected Intent: GetEventsOnDateIntent
> Actual Intent: AllCategoryIntent

Update: fixed by e5f3ccc81cf8b9faff050bf0393de7587e4d4c89

**Comment by ghost** [comment]
> 6
> Utterance: What's tomorrow
> Expected Intent: GetEventsOnDateIntent
> Actual Intent: NextEventIntent

Update: fixed by e5f3ccc

**Comment by ghost** [comment]
I'm closing this because all the quirks listed here have been fixed. The tree is currently undergoing some big changes, so a new issue may be started for new quirks that are encountered.
