### ISSUE TITLE
Delete Duplicate Utterances

### ISSUE THREAD

**Issue by eBucher** [370-Alexa-Project/CS370_Echo_Demo#67]
When the .md file is used to create utterances, there are 2 different utterances that have duplicates.

- "NextEventIntent an event that is next" appears twice.
- NextEventIntent an event that's next" appears twice.

The .md file should be modified that these two lines are only produced one time each.

**Comment by ezquire** [comment]
gonna close this if nobody objects?

**Comment by ezquire** [comment]
fixed in c150090aa9db541aad75728a7558a099b3839089

**Comment by ezquire** [comment]
probably still want to cut down the sheer amount we have, not super important but it would be nice.

**Comment by ghost** [comment]
All utterances are now unique in the ssu-calendar branch.
