### ISSUE TITLE
Figure out how to get alexa out of "stoner mode"

### ISSUE THREAD

**Issue by ezquire** [370-Alexa-Project/CS370_Echo_Demo#72]
Currently she does this:

User: "Alexa, pause"                                                           //this is in the middle of the interaction 
Alexa: "I'm sorry, I forgot what we were talking about"     //back to stoner mode

Somewhere we need to handle the built in navigation intents, i'm not sure if that's an utterance thing or a response thing in the java.

**Comment by ezquire** [comment]
User: "Alexa, tell boo I want to hear about art."
Alexa: "Sorry, I forgot what we were talking about."

another example using the art intent

**Comment by ezquire** [comment]
being worked on in the slot-test branch

**Comment by ezquire** [comment]
as far as the Built-In intents are concerned "stoner mode" is just about stamped out...going to test asking specific category names today

**Comment by ghost** [comment]
Though there are still ways to trigger the bad state response, the most egregious cases of this seem to have been resolved.

Finding better ways to respond in bad states should be a separate issue, so this one is getting closed.
